Add toggle and togglegroup headless and styled components
qwikifiers/qwik-ui pull request #957
Opened 2024-09-02 19:30 UTC by steffanek

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests
- [ ] Other

# Why is it needed?

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have ran `pnpm change` and documented my changes
- [ ] I have add necessary docs (if needed)
- [ ] Added new tests to cover the fix / functionality

2024-09-02 19:31 UTC, steffanek commented
I have read the CLA Document and I hereby sign the CLA

2024-09-03 14:51 UTC, thejackshelton commented
I noticed that when there is not a pressed toggle, then the tab order skips the entire component. Is that the intended behavior? Intuitively my thoughts were it would focus the first focusable toggle button.

Here's a preview:

https://github.com/user-attachments/assets/1d990840-1c7c-401b-82dc-56cf98aa092a

2024-09-04 18:34 UTC, thejackshelton requested changes

2024-09-08 13:22 UTC, steffanek commented on apps/website/src/routes/docs/styled/toggle-group/index.mdx
> +const Root = component$<ToggleGroupRootProps>(({ size, look, ...props }) => {
I haven't used inline component.

2024-09-08 13:23 UTC, steffanek commented on packages/kit-headless/src/components/toggle-group/toggle-group-root.tsx
> +export const HToggleGroupRoot = component$<ToggleGroupRootProps>((props) => {
I find a workaround to get items in order in CSR land.

2024-09-11 01:50 UTC, thejackshelton-kunaico requested changes

2024-09-11 01:50 UTC, thejackshelton-kunaico commented on apps/website/src/routes/docs/styled/toggle/index.mdx
> +An initial, uncontrolled value can be provided using the `defaultPressed` prop.
We need to update the styled docs here, or remove this and refer to headless

2024-09-11 01:50 UTC, thejackshelton-kunaico commented on packages/kit-headless/src/utils/bound-signal2.tsx
> +export const useBoundSignal = <T,>(
Let's go ahead and remove this, since this isn't two way data binding

2024-09-14 19:39 UTC, merged